### PR TITLE
Made the Readme.md file cooler and better

### PR DESCRIPTION
**Pull request by SAQLAINAP**
# Made the **readme.md file** for describing the repository much more _funky and attractive_. 
---
## With this new, cooler version, the contribution guidelines should now be more engaging and exciting, while still giving all the essential information contributors need.

### CODE REVIEW

**Comment by SAQLAINAP** [comment]
Please merge this issue under the **_hacktoberfest_** label. 
@Reterics @jayskhatri @A-4-Atom @jalaym825

**Comment by jalaym825** [comment]
Hey @SAQLAINAP 
Good work! Can you write same kind if README.md for our frontend repo.?

**Comment by SAQLAINAP** [comment]
> Hey @SAQLAINAP Good work! Can you write same kind if README.md for our frontend repo.?

Yeah sure i could do that too.

**Comment by jalaym825** [comment]
> > Hey @SAQLAINAP Good work! Can you write same kind if README.md for our frontend repo.?
> 
> Yeah sure i could do that too.

ok thanks, here's the link: https://github.com/clubgamma/club-gamma-backend

**Pull request merged**
